forum/urls.py
from django.conf.urls import patterns, include, url
from forum.forms.user import LoginForm

from views import common, user, topic, notification
from forum.sitemap import TopicSitemap

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xp.views.home', name='home'),
    # url(r'^xp/', include('xp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', common.method_splitter, {'GET': topic.get_index}),
    url(r'^t/(\d+)/$', common.method_splitter, {'GET': topic.get_view, 'POST': topic.post_view}),
    url(r'^t/create/(.*)/$', common.method_splitter, {'GET': topic.get_create, 'POST': topic.post_create}),
    url(r'^t/edit/(.*)/$', common.method_splitter, {'GET': topic.get_edit, 'POST': topic.post_edit}),
    url(r'^reply/edit/(.*)/$', common.method_splitter, {'GET': topic.get_reply_edit, 'POST': topic.post_reply_edit}),
    url(r'^node/(.*)/$', common.method_splitter, {'GET': topic.get_node_topics}),
    url(r'^u/(.*)/topics/$', common.method_splitter, {'GET': topic.get_user_topics}),
    url(r'^u/(.*)/replies/$', common.method_splitter, {'GET': topic.get_user_replies}),
    url(r'^u/(.*)/favorites/$', common.method_splitter, {'GET': topic.get_user_favorites}),
    url(r'^u/(.*)/$', common.method_splitter, {'GET': topic.get_profile}),
    url(r'^vote/$', common.method_splitter, {'GET': topic.get_vote}),
    url(r'^favorite/$', common.method_splitter, {'GET': topic.get_favorite}),
    url(r'^unfavorite/$', common.method_splitter, {'GET': topic.get_cancel_favorite}),
    url(r'^notifications/$', common.method_splitter, {'GET': notification.get_list}),
    url(r'^members/$', common.method_splitter, {'GET': topic.get_members}),
    url(r'^setting/$', common.method_splitter, {'GET': user.get_setting, 'POST': user.post_setting}),
    url(r'^setting/avatar/$', common.method_splitter, {'GET': user.get_setting_avatar, 'POST': user.post_setting_avatar}),
    url(r'^setting/password/$', common.method_splitter, {'GET': user.get_settingpwd, 'POST': user.post_settingpwd}),
    url(r'^forgot/$', common.method_splitter, {'GET': user.get_forgotpwd, 'POST': user.post_forgotpwd}),
    url(r'^login/$', common.method_splitter, {'GET': user.get_login, 'POST': user.post_login}),
    url(r'^logout/$', common.method_splitter, {'GET': user.get_logout}),
    url(r'^register/$', common.method_splitter, {'GET': user.get_register, 'POST': user.post_register}),

    url(r'^sitemap\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': {'topics': TopicSitemap}}),
)

xp/urls.py
# coding: utf-8

from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib.auth.decorators import login_required
from django.contrib import admin
admin.autodiscover()
admin.site.login = login_required(admin.site.login) # 设置admin登录的页面，settings.LOGIN_URL

import forum.urls

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xp.views.home', name='home'),
    # url(r'^xp/', include('xp.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^', include(forum.urls)),
    url(r'^manage/admin/', include(admin.site.urls)),
)

forum/models.py
#coding: utf-8

from django.db import models
from django.contrib.auth.models import AbstractUser


# 工具
class Pages(object):
    '''
    分页查询类
    '''
    def __init__(self, count, current_page=1, list_rows=40):
        self.total = count
        self._current = current_page
        self.size = list_rows
        self.pages = self.total // self.size + (1 if self.total % self.size else 0)

        if (self.pages == 0) or (self._current < 1) or (self._current > self.pages):
            self.start = 0
            self.end = 0
            self.index = 1
        else:
            self.start = (self._current - 1) * self.size
            self.end = self.size + self.start
            self.index = self._current
        self.prev = self.index - 1 if self.index > 1 else self.index
        self.next = self.index + 1 if self.index < self.pages else self.index


# 数据库字段类型定义
class NormalTextField(models.TextField):
    '''
    models.TextField 默认在MySQL上的数据类型是longtext，用不到那
    么大，所以派生NormalTextField，只修改生成SQL时的数据类型text
    '''
    def db_type(self, connection):
        return 'text'


# Model objects
class NodeManager(models.Manager):
    '''
    Node objects
    '''
    def get_all_hot_nodes(self):
        query = self.get_query_set().filter(topic__reply_count__gt=0).order_by('-topic__reply_count')
        query.query.group_by = ['id'] # Django使用GROUP BY方法
        return query


class TopicManager(models.Manager):
    '''
    Topic objects
    '''
    def get_all_topic(self, num=36, current_page=1): # 可以考虑在这里过滤掉没有头像的用户发帖，不显示在主页
        count = self.get_query_set().count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('node', 'author', 'last_replied_by').\
            all().order_by('-last_touched', '-created', '-last_replied_time', '-id')[page.start:page.end]
        return query, page

    def get_all_topics_by_node_slug(self, num = 36, current_page = 1, node_slug = None):
        count = self.get_query_set().filter(node__slug=node_slug).count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('node', 'author', 'last_replied_by').\
            filter(node__slug=node_slug).order_by('-last_touched', '-created', '-last_replied_time', '-id')[page.start:page.end]
        return query, page

    def get_user_all_topics(self, uid, num = 36, current_page = 1):
        count = self.get_query_set().filter(author__id=uid).count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('node', 'author', 'last_replied_by').\
            filter(author__id=uid).order_by('-id')[page.start:page.end]
        return query, page

    def get_user_all_replied_topics(self, uid, num = 36, current_page = 1):
        pass # F2E好像写的不对，留着以后有用再说

    def get_topic_by_topic_id(self, topic_id):
        query = self.get_query_set().select_related('node', 'author', 'last_replied_by').get(pk=topic_id)
        return query

    def get_user_last_created_topic(self, uid):
        query = self.get_query_set().filter(author__id=uid).order_by('-created')[0]
        return query


class ReplyManager(models.Manager):
    '''
    Reply objects
    '''
    def get_all_replies_by_topic_id(self, topic_id, num = 16, current_page = 1):
        count = self.get_query_set().filter(topic__id=topic_id).count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('author').\
            filter(topic__id=topic_id).order_by('id')[page.start:page.end]
        return query, page

    def get_user_all_replies(self, uid, num = 16, current_page = 1):
        count = self.get_query_set().filter(author__id=uid).count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('topic', 'topic__author').\
            filter(author__id=uid).order_by('-id')[page.start:page.end]
        return query, page


class FavoriteManager(models.Manager):
    '''
    favorite objects
    '''
    def get_user_all_favorites(self, uid, num = 16, current_page = 1):
        count = self.get_query_set().filter(owner_user__id=uid).count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('involved_topic', 'involved_topic__node', \
            'involved_topic__author', 'involved_topic__last_replied_by').\
            filter(owner_user__id=uid).order_by('-id')[page.start:page.end]
        return query, page


class NotificationManager(models.Manager):
    '''
    Notification objects
    '''
    def get_user_all_notifications(self, uid, num = 16, current_page = 1):
        count = self.get_query_set().filter(involved_user__id=uid).count()
        page = Pages(count, current_page, num)
        query = self.get_query_set().select_related('trigger_user', 'involved_topic').\
            filter(involved_user__id=uid).order_by('-id')[page.start:page.end]
        return query, page


# 数据库表结构
class ForumUser(AbstractUser):
    '''
    django.contrib.auth.models.User 默认User类字段太少，用AbstractUser
    自定义一个User类，增加字段
    '''
    nickname = models.CharField(max_length=200, null=True, blank=True)
    avatar = models.CharField(max_length=200, null=True, blank=True)    # 头像
    signature = models.CharField(max_length=500, null=True, blank=True) # 签名
    location = models.CharField(max_length=200, null=True, blank=True)
    website = models.URLField(null=True, blank=True)
    company = models.CharField(max_length=200, null=True, blank=True)
    role = models.IntegerField(null=True, blank=True)                   # 角色
    balance = models.IntegerField(null=True, blank=True)                # 余额
    reputation = models.IntegerField(null=True, blank=True)             # 声誉
    self_intro = models.CharField(max_length=500, null=True, blank=True)# 自我介绍
    updated = models.DateTimeField(null=True, blank=True)
    twitter = models.CharField(max_length=200, null=True, blank=True)
    github = models.CharField(max_length=200, null=True, blank=True)
    douban = models.CharField(max_length=200, null=True, blank=True)


class Plane(models.Model):
    '''
    论坛节点分类
    '''
    name = models.CharField(max_length=200, null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)


class Node(models.Model):
    '''
    论坛板块单位，节点
    '''
    name = models.CharField(max_length=200, null=True, blank=True)
    slug = models.CharField(max_length=200, null=True, blank=True)          # 块，作为node的识别url
    thumb = models.CharField(max_length=200, null=True, blank=True)         # 拇指?
    introduction = models.CharField(max_length=500, null=True, blank=True)  # 介绍
    created = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    plane = models.ForeignKey(Plane, null=True, blank=True)
    topic_count = models.IntegerField(null=True, blank=True)
    custom_style = NormalTextField(null=True, blank=True)
    limit_reputation = models.IntegerField(null=True, blank=True) # 最小声誉，估计是权限控制

    objects = NodeManager()


class Topic(models.Model):
    '''
    话题表，定义了论坛帖子的基本单位
    '''
    title = models.CharField(max_length=200, null=True, blank=True)
    content = NormalTextField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    hits = models.IntegerField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    node = models.ForeignKey(Node, null=True, blank=True)
    author = models.ForeignKey(ForumUser, related_name='topic_author', null=True, blank=True) # 设置了related_name后，可不用_set
    reply_count = models.IntegerField(null=True, blank=True)
    last_replied_by = models.ForeignKey(ForumUser, related_name='topic_last', null=True, blank=True)
    last_replied_time = models.DateTimeField(null=True, blank=True)
    up_vote = models.IntegerField(null=True, blank=True)
    down_vote = models.IntegerField(null=True, blank=True)
    last_touched = models.DateTimeField(null=True, blank=True)

    objects = TopicManager()


class Reply(models.Model):
    '''
    话题的回复
    '''
    topic = models.ForeignKey(Topic, null=True, blank=True)
    author = models.ForeignKey(ForumUser, related_name='reply_author', null=True, blank=True)
    content = NormalTextField(null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)
    updated = models.DateTimeField(null=True, blank=True)
    up_vote = models.IntegerField(null=True, blank=True)
    down_vote = models.IntegerField(null=True, blank=True)
    last_touched = models.DateTimeField(null=True, blank=True)

    objects = ReplyManager()


class Favorite(models.Model):
    '''
    用户收藏的话题或回复
    '''
    owner_user = models.ForeignKey(ForumUser, related_name='fav_user', null=True, blank=True)
    involved_type = models.IntegerField(null=True, blank=True)
    involved_topic = models.ForeignKey(Topic, related_name='fav_topic', null=True, blank=True)
    involved_reply = models.ForeignKey(Reply, related_name='fav_reply', null=True, blank=True)
    created = models.DateTimeField(null=True, blank=True)

    objects = FavoriteManager()


class Notification(models.Model):
    '''
    通知消息
    '''
    content = NormalTextField(null=True, blank=True)
    status = models.IntegerField(null=True, blank=True)
    involved_type = models.IntegerField(null=True, blank=True)
    involved_user = models.ForeignKey(ForumUser, related_name='notify_user', null=True, blank=True)
    involved_topic = models.ForeignKey(Topic, related_name='notify_topic', null=True, blank=True)
    involved_reply = models.ForeignKey(Reply, related_name='notify_reply', null=True, blank=True)
    trigger_user = models.ForeignKey(ForumUser, related_name='notify_trigger', null=True, blank=True)
    occurrence_time = models.DateTimeField(null=True, blank=True)

    objects = NotificationManager()


class Transaction(models.Model):

forum/forms/topic.py
# coding: utf-8

from django import forms

class ReplyForm(forms.Form):
    content = forms.CharField(error_messages={
        'required': u'请填写回复内容',})


class CreateForm(forms.Form):
    title = forms.CharField(min_length=3, max_length=56,
        error_messages={
            'required': u'请填写帖子标题',
            'min_length': u'帖子标题长度过短（3-56个字符）',
            'max_length': u'帖子标题长度过长（3-56个字符）',
        })
    content = forms.CharField(min_length=15,
        error_messages={
            'required': u'请填写帖子内容',
            'min_length': u'帖子内容长度过短（少于15个字符）',
        })

forum/views/common.py
# coding: utf-8

import re
from django.core.mail import EmailMultiAlternatives
from django.http import Http404
from django.conf import settings


def method_splitter(request, *args, **kwargs):
    get_view = kwargs.pop('GET', None)
    post_view = kwargs.pop('POST', None)
    if request.method == 'GET' and get_view is not None:
        return get_view(request, *args, **kwargs)
    elif request.method == 'POST' and post_view is not None:
        return post_view(request, *args, **kwargs)
    raise Http404

def sendmail(title, content, to):
    msg = EmailMultiAlternatives(title, content, settings.DEFAULT_FROM_EMAIL, [to])
    msg.attach_alternative(content, 'text/html')
    msg.send()


def find_mentions(content):
    regex = re.compile(ur'@(?P<username>\w+)(\s|$)', re.I)
    return set([m.group('username') for m in regex.finditer(content)])

forum/views/notification.py
# coding: utf-8

from django.shortcuts import render_to_response
from django.contrib.auth.decorators import login_required
from django.template import RequestContext
from forum.models import Notification


@login_required
def get_list(request):
    current_page = int(request.GET.get('p', '1'))
    user = request.user
    counter = {
        'topics': user.topic_author.all().count(),
        'replies': user.reply_author.all().count(),
        'favorites': user.fav_user.all().count()
    }

    notifications_count = user.notify_user.filter(status=0).count()
    notifications, page = Notification.objects.get_user_all_notifications(user.id, current_page=current_page)
    active_page = 'topic'

    user.notify_user.filter(status=0).update(status=1) # 未读消息设置为已读

    return render_to_response('notification/notifications.html', locals(),
        context_instance=RequestContext(request))

forum/templates/topic/create.html
{% extends 'snippet/layout.html' %}
{% load forum_extras %}

{% block javascript %}
    <script type="text/x-mathjax-config">
        MathJax.Hub.Config({
            tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]}
        });
    </script>
    <script type="text/javascript" src="https://c328740.ssl.cf1.rackcdn.com/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
    <script type="text/javascript" src="/static/js/widget/emmet.min.js"></script>
    <script type="text/javascript" src="/static/js/widget/jquery.textarea.min.js"></script>
    <script type="text/javascript">
        jQuery(document).ready(function() {
            $('textarea.smart-code-support').tabby();
            emmet.require('textarea').setup({
                pretty_break: false, // enable formatted line breaks (when inserting // between opening and closing tag)
                use_tab: false       // expand abbreviations by Tab key
            });
        });
    </script>
{% endblock %}

{% block main %}
    <div class="topic-create container-box">
        <div class="ui-header">
            <span class="title">创建新主题</span>
        </div>

        <div class="ui-content">
            <form class="mt10" action="/t/create/{{ node_slug }}/" method="post">
                {{ errors|dump_errors }}
                <div class="input-prepend mt10">
                    <span class="add-on">#</span>
                    <input class="span11" id="prependedInput" type="text" placeholder="主题" name="title">
                </div>
                <textarea rows="3" class="content mt5 smart-code-support" placeholder="正文" name="content"></textarea>
                <input type="submit" id="checkall" class="btn btn-small" value="立即创建">
                {% csrf_token %}
            </form>
        </div>
    </div>
{% endblock %}

{% block sidebar %}
    <div class="usercard container-box">
        <div class="ui-header">
            <a href="/u/{{ user.username }}/">
                <img src="/static/avatar/m_{% if user.avatar %}{{ user.avatar }}{% else %}default.png{% endif %}?t={% gen_random %}" alt="" class="avatar" />
            </a>
            <div class="username">{{ user.username }}</div>
            <div class="website"><a href="{% if user.website %}{{ user.website }}{% endif %}">{% if user.website %}{{ user.website }}{% endif %}</a></div>
        </div>
        <div class="ui-content">
            <div class="status status-topic">
                <strong><a href="/u/{{ user.username }}/topics/">{{ counter.topics }}</a></strong> 主题
            </div>
            <div class="status status-reply">
                <strong><a href="/u/{{ user.username }}/replies/">{{ counter.replies }}</a></strong> 回复
            </div>
            <div class="status status-favorite">
                <strong><a href="/u/{{ user.username }}/favorites/">{{ counter.favorites }}</a></strong> 收藏
            </div>
            <div class="status status-reputation">
                <strong>{% if user.reputation %}{{ user.reputation }}{% else %}0{% endif %}</strong> 威望
            </div>
        </div>
    </div>
{% endblock %}

forum/templates/topic/topics.html
{% extends 'snippet/layout.html' %}
{% load forum_extras %}

{% block main %}
    {% comment %}
    <ul class="news container-box">
        <li><a href="#">HTML5(目前)无法帮你实现的五件事</a></li>
        <li><a href="#">DNS优化的原理和方法</a></li>
        <li><a href="#">浅谈互联网产品前期设计方法</a></li>
        <li><a href="#">如何在Google成为优秀的产品经理?</a></li>
        <li><a href="#">页面前端的水有多深？</a></li>
        <li><a href="#">如何利用互联网工具调研网站</a></li>
    </ul>
    {% endcomment %}

    <div class="topics container-box deprecated-mt10">
        <div class="ui-header">
            <div class="dropdown fr">
                <a class="btn btn-small" type="button" href="###" data-toggle="dropdown">创建新主题</a>
                <ul class="dropdown-menu" role="menu">
                    <li role="presentation">
                        {% for node in hot_nodes %}
                        <a role="menuitem" href="/t/create/{{ node.slug }}/">{{ node.name }}</a>
                        {% endfor %}
                    </li>
                </ul>
            </div>
            <span class="bread-nav">
                {# 在这里写你自己写推荐的node,或者其它链接,参考F2E.im #}
                <a class="node-link" href="/node/share/">分享</a>
            </span>
        </div>
        {% for topic in topics %}
            <div class="topic-item">
                <a href="/u/{{ topic.author.username }}/">
                    <img src="/static/avatar/m_{% if topic.author.avatar %}{{ topic.author.avatar }}{% else %}default.png{% endif %}" alt="" class="avatar" />
                </a>
                <div class="main">
                    <h3 class="title">
                        <a href="/t/{{ topic.id }}/">{{ topic.title }}</a>
                    </h3>
                    <div class="meta">
                        <span class="node"><a href="/node/{{ topic.node.slug }}/">{{ topic.node.name }}</a></span> •
                        <span class="username">
                            <a href="/u/{% if topic.author.username %}{{ topic.author.username }}{% else %}{{ topic.author.id }}{% endif %}/">{{ topic.author.username }}</a>
                        </span> •
                        {% if topic.last_replied_time %}
                            <span class="last-touched">{{ topic.last_touched|pretty_date }}</span> •
                            <span class="last-reply-username">最后回复来自
                                <a href="/u/{% if topic.last_replied_by.username %}{{ topic.last_replied_by.username }}{% else %}{{ topic.last_replied_by.id }}{% endif %}/">
                                    <strong>{{ topic.last_replied_by.username }}</strong>
                                </a>
                            </span>
                        {% else %}
                            <span class="last-touched">{{ topic.last_touched|pretty_date }}</span>
                        {% endif %}
                    </div>
                </div>
                {% if topic.reply_count %}
                    <div class="count">
                        <a href="/t/{{ topic.id }}/#reply{% if topic.reply_count %}{{ topic.reply_count }}{% else %}0{% endif %}">{% if topic.reply_count %}{{ topic.reply_count }}{% else %}0{% endif %}</a>
                    </div>
                {% endif %}
            </div>
        {% endfor %}

        {% if topic_page.pages > 1 %}
        <div class="pagination">
            {% pagination topic_page request.get_full_path %}
        </div>
        {% endif %}
    </div>

    <div class="nodes-cloud container-box mt10">
        <h4 class="title">
            <span class="octicon octicon-globe"></span>
            常见节点导航
        </h4>
        <ul>
            {% for plane in planes %}
                <li>
                    <label for="">{{ plane.name }}</label>
                    <span class="nodes">
                        {% for node in plane.node_set.all %}
                            <a href="/node/{{ node.slug }}/">{{ node.name }}</a>
                        {% endfor %}
                    </span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endblock %}

{% block sidebar %}
    {% if user.is_authenticated %}
        <div class="usercard container-box">
            <div class="ui-header">
                <a href="/u/{{ user.username }}/">
                    <img src="/static/avatar/m_{% if user.avatar %}{{ user.avatar }}{% else %}default.png{% endif %}?t={% gen_random %}" alt="" class="avatar" />
                </a>
                <div class="username">{{ user.username }}</div>
                <div class="website"><a href="{% if user.website %}{{ user.website }}{% endif %}">{% if user.website %}{{ user.website }}{% endif %}</a></div>
            </div>
            <div class="ui-content">
                <div class="status status-topic">
                    <strong><a href="/u/{{ user.username }}/topics/">{{ counter.topics }}</a></strong> 主题
                </div>
                <div class="status status-reply">
                    <strong><a href="/u/{{ user.username }}/replies/">{{ counter.replies }}</a></strong> 回复
                </div>
                <div class="status status-favorite">
                    <strong><a href="/u/{{ user.username }}/favorites/">{{ counter.favorites }}</a></strong> 收藏
                </div>
                <div class="status status-reputation">
                    <strong>{% if user.reputation %}{{ user.reputation }}{% else %}0{% endif %}</strong> 威望
                </div>
            </div>
        </div>
        {% comment %}
        {% if user.counter.notifications %}
            <div class="alert mt10 mb10">
                <span>
                    <a href="/notifications/">{% if user.nickname %}{{ user.nickname }}{% else %}{{ user.nickname }}{% endif %}，你有{{ user.counter.notifications }}条未读提醒，去看看吧</a>
                </span>
            </div>
        {% endif %}
        {% endcomment %}
    {% else %}
        <div class="login-box container-box">
            <div class="ui-content tc">
                <a class="btn btn-small mr10" type="button" href="/login/">登录</a>
                <a class="btn btn-small mr10" type="button" href="/register/">注册</a>
                <a class="btn btn-small" type="button" href="/forgot/">找回密码</a>
            </div>
        </div>
    {% endif %}

    <div class="sidebox container-box mt10 weixin">
        <div class="ui-header">
            <span class="title">微信公共帐号</span>
        </div>
        <div class="ui-content">
            <img src="/static/images/qrcode_for_gh_81ac76ebf8e3_258.jpg" alt="" />
        </div>
    </div>

    <div class="sidebox container-box mt10 hot-nodes">
        <div class="ui-header">
            <span class="title">最热节点</span>
        </div>
        <div class="ui-content">
            {% for node in hot_nodes %}
                <a href="/node/{{ node.slug }}/">{{ node.name }}</a>
            {% endfor %}
        </div>
    </div>

    <div class="sidebox container-box mt10 friends">
        <div class="ui-header">
            <span class="title">友情社区</span>
        </div>
        <div class="ui-content">
            <p><a href="http://python-china.org"><img src="/static/images/python_china_logo.jpg" alt="" /></a></p>
            <p><a href="http://ruby-china.org"><img src="/static/images/ruby_china_logo.png" alt="" /></a></p>
            <p><a href="http://trans4fun.org"><img src="/static/images/trans4fun.png" alt="" /></a></p>
            <p><a href="http://www.ubuntusoft.com"><img src="/static/images/ubuntusoft.png" alt="" style="width:190px;" /></a></p>
        </div>
    </div>

    {% comment %}
    <div class="sidebox container-box mt10 friends">
        <div class="ui-header">
            <span class="title">我们的标志</span>
        </div>
        <div class="ui-content">
            <p><a href="http://f2e.im"><img src="/static/images/f2e.im.logo.png" alt="" /></a></p>
        </div>
    </div>
    {% endcomment %}

    <div class="sidebox container-box mt10 community-status">
        <div class="ui-header">
            <span class="title">运行状态</span>
        </div>
        <div class="ui-content">
            <dl>
                <dt>注册成员</dt>
                <dd>{{ status_counter.users }}</dd>
            </dl>
            <dl>
                <dt>节点</dt>
                <dd>{{ status_counter.nodes }}</dd>
            </dl>
            <dl>
                <dt>主题</dt>
                <dd>{{ status_counter.topics }}</dd>
            </dl>
            <dl>
                <dt>回复</dt>
                <dd>{{ status_counter.replies }}</dd>
            </dl>
        </div>
    </div>
</div>
{% endblock %}